import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "./components/contacts/layout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Layout />
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>
			<main className={`${styles.main} ${inter.className}`}>
				<div className={styles.description}>
					<p>
						Get started by editing&nbsp;
						<code className={styles.code}>pages/index.js</code>
					</p>
					<div>
						<a
							href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
							target="_blank"
							rel="noopener noreferrer">
							By{" "}
							<Image
								src="/vercel.svg"
								alt="Vercel Logo"
								className={styles.vercelLogo}
								width={100}
								height={24}
								priority
							/>
						</a>
					</div>
				</div>

				<div className={styles.center}>
					<Image
						className={styles.logo}
						src="/next.svg"
						alt="Next.js Logo"
						width={180}
						height={37}
						priority
					/>
				</div>

				<div className={styles.center}>
					<h1>Welcome to my Elearning site</h1>
				</div>

				<div className={styles.grid}>
					<Link
						href="learn/next"
						className={styles.card}>
						<h2>
							Learn Next <span>-&gt;</span>
						</h2>
						<p>
							Find in-depth information about Next.js features and&nbsp;API.
						</p>
					</Link>
					<Link
						href="learn/react"
						className={styles.card}>
						<h2>
							Learn React <span>-&gt;</span>
						</h2>
						<p>
							Learn about ReactJS in an interactive course with&nbsp;quizzes!
						</p>
					</Link>
					<Link
						href="learn/vue"
						className={styles.card}>
						<h2>
							Learn Vue <span>-&gt;</span>
						</h2>
						<p>
							Learn about ReactJS in an interactive course with&nbsp;quizzes!
						</p>
					</Link>

					<Link
						href="learn/angular"
						className={styles.card}>
						<h2>
							Learn Angular <span>-&gt;</span>
						</h2>
						<p>
							Learn about ReactJS in an interactive course with&nbsp;quizzes!
						</p>
					</Link>
				</div>
			</main>
		</>
	);
}
